### ISSUE TITLE
Problem in config file, unexpected '('

### ISSUE THREAD

**Issue by maxim-kyryliuk** [PalFed/sslChecker#1]
Unexpected '(' on some system

https://github.com/PalFed/SSL-Expiry-Checker/blob/154698bab495ec371f433141ef5dad1b4ed70e16/sslChecker.ini.php#L2

Suggestion: Remove this line or remove "()".

**Comment by PalFed** [comment]
Sorry for the delay! I have made the change as you suggested. Thanks!
