### ISSUE TITLE
Case sensitivity problem

### ISSUE THREAD

**Issue by maxim-kyryliuk** [PalFed/sslChecker#2]
Got problem in case sensitivity system. Name of the file here should be same like in repo. 

https://github.com/PalFed/SSL-Expiry-Checker/blob/154698bab495ec371f433141ef5dad1b4ed70e16/sslChecker.php#L98

Suggestion: Rename file in repo or rename path to file in PHP code, from sslchecker.php to sslChecker.php

**Comment by PalFed** [comment]
Sorry for the delay! I have updated the code as you suggested. Thanks!
